#!/usr/bin/env Rscript
# Imputes cell type to .rds generated by 'seu_integrate_DeOp.R'
# input: 
#   txt file ==> all specific markers from experience
#   txt file => reference markers
#   rds file 
# output : .rds file containing corresponding celltypes (vector)
#        and figures
# --
# JohaGL

library(dplyr)
library(tidyverse)
library(Seurat)
library(ggplot2)
library(sctransform)
library(cowplot)
library(RColorBrewer)
source(file="~/INMG_SingleCell/scripts/functions_stock.R",local=T)

prloc="~/INMG_SingleCell/"
setwd(prloc)

# colors to distinguish author origin:
ctrans <- c( rgb(0.4, 0.77, 0.50, alpha=0.5),
             rgb(0.15, 0.34, 0.95, alpha=0.4)
            )
#   Markers groups and celltypes as discussed with Dr Le Grand:
ref = "refmarkers/newRefmarkersToCells_V2.txt" # >>check: USE V2 *
ref = "refmarkers/newRefmarkersToCells_v1.txt"
refDF <- read.table(ref,sep="\t",header=TRUE)
head(refDF,n=2)

# integrated: paths
prefix="DeOp"
delimiter = "\t" # TAB delimited in this integrated MARKERS
resu="results/integratedD0_DeOp/"
rdsdir = "rds/integratedD0_DeOp/"
seufile = paste0(prefix,"_integrated_seu_fitsne.rds")
markersinresults = paste0(prefix,"_ALLMARKERS_Pos_integratedD0.txt")
outsuffix=paste0(prefix,"_integr_celltype_Vector.rds")

# remember: use reference V2
# NEW: Get not only seurat object but also its corresponding n top markers 
seu.mk <- NEWCustomImputeCelltype(refDF, resu, markersinresults, delimiter,
                                          rdsdir, seufile, outsuffix,5)

names(seu.mk) = c("seu","mk") 
muscle.integrated = seu.mk[["seu"]]
mk = seu.mk[["mk"]]
rm(seu.mk)

COL=definecolors(muscle.integrated@active.ident)

##  see interesting features
pdf(paste0(resu,paste0(prefix, "_interestingFeatures.pdf")))
lplo <- FeaturePlot(muscle.integrated, features=c("Smoc2","Pi16", "Sfrp5", "Hic1",
                                                  "Pax7","Cd34", "Notch2"),combine=F)
index=length(lplo)-1
for (i in 1:index){
  lplo[[i]] <- lplo[[i]] + theme(text=element_text(size=9), legend.position="none")
}
lplo[[length(lplo)]] <- lplo[[length(lplo)]] + theme(text=element_text(size=9))
plot_grid(plotlist=lplo,ncol=3)
dev.off()

pdf(paste0(resu,prefix,"_FITSNEandUMAP_named.pdf"), width=9)
uma1 <- DimPlot(muscle.integrated, reduction="umap", group.by = "orig.ident" ,pt.size=0.05,
                cols=ctrans, label.size = 3)+ theme(text = element_text(size=10))
uma2 <- DimPlot(muscle.integrated, reduction="umap", label=T, repel=T,
               cols=COL, label.size = 3) + theme(text = element_text(size=10))
fit1 <- DimPlot(muscle.integrated, reduction="tsne", group.by = "orig.ident" ,pt.size=0.05,
                cols=ctrans, label.size = 3) + theme(text = element_text(size=10))
fit2 <- DimPlot(muscle.integrated, reduction="tsne", label=T, repel=T,
                cols=COL, label.size = 3)+ theme(text = element_text(size=10))
plot_grid(uma1, uma2,fit1,fit2,nrow=2, rel_widths = c(4,5))
dev.off()

print("NEW: Sending HEATMAP containing named clusters")
# #if less markers desired:
# myMK <- mk %>% group_by(cluster) %>% top_n(n=4, wt= avg_logFC)
pdf(paste0(resu,prefix,"_HEATMAP_named.pdf"), width=11, height = 9)
DoHeatmap(muscle.integrated, features = as.character(mk$gene), group.bar=T ,
          group.colors=COL, size=2) +
  theme(legend.position = "bottom", axis.text = element_text(size=7))
dev.off()

print("finished")


# ##
# ## load ancient integr oprescu 
# load("/run/media/johanna/TOSHIBA EXT/2jul/reanalysesPubs/integrD0_DMich_Oprescu_ok/Opres_DeMich_umap_17markers.RData")
# head(muscle.integrated.markers)
# rm(muscle.integrated)
# coucou <- readRDS("rds/integratedD0_DeOp/Opres_DeMichseu_withNames.rds")
# 
# mumu <- muscle.integrated.markers %>% filter(avg_logFC>0) 
# mumu <- mumu %>% group_by(cluster) %>% top_n(n=10,wt=avg_logFC)
# crazydf <- data.frame(coucou@active.ident,coucou@meta.data$seurat_clusters)
# crazydf <- crazydf %>% distinct(coucou.active.ident,coucou.meta.data.seurat_clusters) %>%
#   arrange(coucou.meta.data.seurat_clusters)
# rownames(crazydf) = crazydf$coucou.meta.data.seurat_clusters
# colnames(crazydf) = c("clusternames", "cluster")
# fusion = left_join(mumu,crazydf, by="cluster")
# write.table(fusion, "refmarkers/markers_oldIntegrationMan.txt",col.names = T, sep="\t")
# reduced = fusion %>% select(clusternames,gene)
# reduced$cluster = NULL
# write.table(reduced, "refmarkers/newRefmarkersToCell_V2.txt",col.names = T, sep="\t")